### ISSUE TITLE
How to install igraph on OSX (Yosemite 10.10.1)

### ISSUE THREAD

**Issue by cudmore** [cmicek1/TiffViewer#2]
How to install igraph in Anaconda on OSX (Yosemite 10.10.1).

1. Uninstall igraph that comes with Anaconda
>     pip uninstall igraph

2. Install [homebrew](https://brew.sh/)

3. Using homebrew, install pkg-config
>    brew install pkg-config

4. install python-igraph using pip
>    pip install python-igraph

If python-igraph fails with errors like:

>     grep: /usr/lib/libiconv.la: No such file or directory
>     sed: /usr/lib/libiconv.la: No such file or directory
>     libtool: link: `/usr/lib/libiconv.la' is not a valid libtool archive
>     make[3]: *** [libigraph.la] Error 1
>     make[2]: *** [all] Error 2
>     make[1]: *** [all-recursive] Error 1
>     make: *** [all] Error 2
>     Could not download and compile the C core of igraph.
> 

Make sure you have used homebrew to install both `homebrew/science/igraph` and `pkg-config`. See [this](http://stackoverflow.com/questions/29589696/problems-compiling-c-core-of-igraph-with-python-2-7-9-anaconda-2-2-0-on-mac-osx) on StackOverflow for more help. The idea is that using homebrew to install pkg-config and possibly homebrew/science/igraph will fix the error.

**Comment by cudmore** [comment]
we need to get this into a little readme for installing. Can you link igraph in your dependency list in readme.md. Can you also remove pygame form dependencies and maybe make a little seciton at the end saying, 'here is the older and depreciated pygame version'.

**Comment by cmicek1** [comment]
Thank you @cudmore for your request. I've since updated the project structure considerably and have revised the list of dependencies for each branch to include links to any potentially obscure 3rd-party packages. Instructions for installing python-igraph on OSX are on the homepage of its website, so I opted not to include them here.
